# -*- coding: utf-8 -*-
"""app_MDR

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eCbbv8mpPeWX6Z_wXApvTAhRRMsqBXxi
"""

import streamlit as st
import os
import cv2
import uuid
import numpy as np
from PIL import Image
import pandas as pd

# Setup
os.makedirs("faces", exist_ok=True)
os.makedirs("prescriptions", exist_ok=True)

st.set_page_config(page_title="May Day Rakshak", layout="centered")
st.title("🛡️ May Day Rakshak (MDR) App")
st.caption("Secure Hospital Entry • Real-time Appointments • Smart Pharmacy")

menu = st.sidebar.radio("Navigate", ["👤 Visitor Entry", "📅 Book Appointment", "💊 Upload Prescription", "📍 Share Help Location"])

# -------------------------------
# Function: Face match using OpenCV
# -------------------------------
def verify_face_opencv(known_img, new_img):
    def detect_face(image):
        face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + "haarcascade_frontalface_default.xml")
        gray = cv2.cvtColor(np.array(image.convert('RGB')), cv2.COLOR_RGB2GRAY)
        faces = face_cascade.detectMultiScale(gray, 1.1, 5)
        return faces
    return len(detect_face(known_img)) > 0 and len(detect_face(new_img)) > 0

# -------------------------------
# Section: Visitor Entry
# -------------------------------
if menu == "👤 Visitor Entry":
    st.header("🧾 Visitor Card Verification")

    visitor_id = st.text_input("Enter Visitor ID (from MDR card)")
    uploaded_photo = st.file_uploader("📷 Upload your face photo to verify", type=['jpg', 'png', 'jpeg'])

    if st.button("🔍 Verify Entry"):
        if not visitor_id or not uploaded_photo:
            st.error("Please provide both ID and a photo.")
        else:
            ref_path = f"faces/{visitor_id}.jpg"
            if os.path.exists(ref_path):
                new_image = Image.open(uploaded_photo)
                ref_image = Image.open(ref_path)
                if verify_face_opencv(ref_image, new_image):
                    st.success("✅ Face Verified. Entry allowed to Doctor/Patient Room.")
                else:
                    st.error("❌ Face mismatch. Access Denied.")
            else:
                # Save uploaded image as reference if not exists
                Image.open(uploaded_photo).save(ref_path)
                st.success("✅ Visitor registered and photo saved.")

# -------------------------------
# Section: Book Appointment
# -------------------------------
elif menu == "📅 Book Appointment":
    st.header("🩺 Real-time Doctor Appointments")

    doctors = [
        {"name": "Dr. Mehta", "specialty": "Cardiologist", "available": "10:00–12:00"},
        {"name": "Dr. Sharma", "specialty": "Neurologist", "available": "12:00–14:00"},
        {"name": "Dr. Patel", "specialty": "Pediatrician", "available": "15:00–17:00"},
    ]

    df = pd.DataFrame(doctors)
    st.dataframe(df)

    choice = st.selectbox("Choose Doctor", df['name'].tolist())
    slot = st.time_input("Select Time")
    if st.button("📥 Book Now"):
        st.success(f"Appointment booked with {choice} at {slot}.")

# -------------------------------
# Section: Upload Prescription
# -------------------------------
elif menu == "💊 Upload Prescription":
    st.header("🧾 Upload Prescription for Hospital Pharmacy")
    visitor_id = st.text_input("Visitor ID (linked with MDR card)")
    presc = st.file_uploader("📷 Upload Prescription Image", type=["jpg", "png", "jpeg"])

    if st.button("🚀 Send to Pharmacy"):
        if visitor_id and presc:
            path = f"prescriptions/{visitor_id}_{uuid.uuid4()}.jpg"
            Image.open(presc).save(path)
            st.success("🧾 Prescription sent to pharmacy. Collect meds after MDR punch.")
        else:
            st.warning("Please provide both Visitor ID and prescription image.")

# -------------------------------
# Section: Share Help Location
# -------------------------------
elif menu == "📍 Share Help Location":
    st.header("📢 Citizen Assist")

    name = st.text_input("Your Name (for reward)")
    lat = st.text_input("Latitude")
    lon = st.text_input("Longitude")
    help_img = st.file_uploader("Upload image of incident/victim", type=["jpg", "png", "jpeg"])

    if st.button("🚨 Alert May Day Team"):
        if name and lat and lon and help_img:
            st.success("🚑 Location and image received. MDR team will reach shortly.")
            st.info(f"🎁 {name}, you earned 100 reward points!")
        else:
            st.error("Please provide full details to assist the victim.")