# -*- coding: utf-8 -*-
"""app_MDR

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eCbbv8mpPeWX6Z_wXApvTAhRRMsqBXxi
"""

import streamlit as st
from PIL import Image
from datetime import datetime
import os

st.set_page_config(page_title="May Day Rakshak", layout="wide")
st.title("🛡️ May Day Rakshak – Better healthcare in climate-sensitive zones")

menu = st.sidebar.selectbox(
    "📋 Navigation",
    [
        "🏠 Home",
        "📝 Register MDR Card",
        "📸 Photo Check-In",
        "📅 Doctor Appointment",
        "💊 Upload Prescription"
    ]
)

if menu == "🏠 Home":
    st.markdown("""
        ### Welcome to **May Day Rakshak (MDR)** 🏥
        A comprehensive system for ensuring **hospital safety, patient comfort**, and **faster medical services**.

        🚪 Secure room/doctor access with face verification
        🕵️ Monitor visitor entry logs via MDR card
        📅 Book doctor appointments with real-time availability
        💊 Send prescriptions directly to the pharmacy and avoid queues
    """)

# ---- Step 1: Register Patient & Visitor ---- #
elif menu == "📝 Register MDR Card":
    st.header("📝 Register for May Day Rakshak Pass")

    name = st.text_input("Full Name")
    relation = st.selectbox("Relation to Patient", ["Parent", "Sibling", "Spouse", "Friend", "Other"])
    contact = st.text_input("Contact Number")
    room = st.text_input("Assigned Room No.")
    bed = st.text_input("Bed No.")
    photo = st.camera_input("📷 Capture Your Face")

    if st.button("Register"):
        if name and contact and room and bed and photo:
            folder = "visitors"
            os.makedirs(folder, exist_ok=True)
            file_path = f"{folder}/{name.replace(' ', '_')}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.jpg"
            with open(file_path, "wb") as f:
                f.write(photo.getbuffer())
            st.success(f"✅ Registered MDR pass for {name}")
        else:
            st.warning("Please fill all fields and click a photo.")

# ---- Step 2: Face Check-In ---- #
elif menu == "📸 Photo Check-In":
    st.header("📸 Verify Entry to Room/Doctor")

    visitor_id = st.text_input("Enter Visitor Name or ID")
    check_photo = st.camera_input("📷 Capture Face for Entry Check")

    if st.button("Verify Entry"):
        if visitor_id and check_photo:
            # In real system: match face using FaceNet or similar
            st.success(f"✅ Visitor '{visitor_id}' checked in successfully.")
        else:
            st.warning("Please provide visitor ID and face photo.")

# ---- Step 3: Book Doctor Appointment ---- #
elif menu == "📅 Doctor Appointment":
    st.header("📅 Book Doctor Appointment")

    doc_speciality = st.selectbox("Select Speciality", ["Cardiology", "Neurology", "Orthopedics", "ENT", "Pediatrics"])
    doc_list = {
        "Cardiology": ["Dr. Mehra", "Dr. Gupta"],
        "Neurology": ["Dr. Bose", "Dr. Awasthi"],
        "Orthopedics": ["Dr. Rana", "Dr. Malhotra"],
        "ENT": ["Dr. Jha", "Dr. Thomas"],
        "Pediatrics": ["Dr. Singh", "Dr. Naik"]
    }

    available_docs = doc_list.get(doc_speciality, [])
    selected_doc = st.selectbox("Choose Doctor", available_docs)

    appt_date = st.date_input("Select Date")
    appt_time = st.time_input("Select Time")

    if st.button("Book Appointment"):
        st.success(f"📅 Appointment confirmed with **{selected_doc}** on {appt_date} at {appt_time}")

# ---- Step 4: Upload Prescription ---- #
elif menu == "💊 Upload Prescription":
    st.header("🧾 Upload Prescription for Hospital Pharmacy")

    visitor_id = st.text_input("Visitor ID (linked with MDR card)")
    presc = st.file_uploader("📷 Upload Prescription Image", type=["jpg", "png", "jpeg"])

    if st.button("🚀 Send to Pharmacy"):
        if visitor_id and presc:
            os.makedirs("prescriptions", exist_ok=True)
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            path = f"prescriptions/{visitor_id}_{timestamp}.jpg"
            with open(path, "wb") as f:
                f.write(presc.read())
            st.success("🧾 Prescription sent to pharmacy. Collect meds after MDR punch.")
        else:
            st.warning("Please provide both Visitor ID and prescription image.")
